project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
]

project/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [

    path('expage', views.expage, name="expage"),
    path('home', views.home, name="home"),
    path('login', views.login, name="login"),
    path('signup', views.signup, name='signup'),
    path('shop', views.shop, name="shop"),
    path('info', views.info, name="info")

]

project/user/models.py
from django.db import models

# Create your models here.

project/user/views.py
from django.shortcuts import render

# Create your views here.

def expage(request):
    return render(request, 'user_templates/expage.html')

def home(request):
    return render(request, 'user_templates/home.html')

def login(request):
    return render(request, 'user_templates/login.html')

def signup(request):
     return render(request, 'user_templates/signup.html')

def shop(request):
    return render(request, 'user_templates/shop.html')

def info(request):
    return render(request, 'user_templates/info.html')

    

project/user/templates/user_templates/expage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/expage.css' %}">
</head>
<body>

<!-- extends used only info page -->



    <div id="nav_bar">
        <div class="nav_left">
            <a href="{% url 'user:signup' %}"><button class="btn">Sign Up</button></a>
            <a href="{% url 'user:home' %}">
                <div class="sub"><b>HOME</b></div>
            </a>
            <a href="">
                <div class="sub"><b>TEAM</b></div>
            </a>
            <a href="{% url 'user:shop' %}">
                <div class="sub"><b>SHOP</b></div>
            </a>
        </div>
        <div class="nav_center">
            <div class="nav_img"><img src="{% static 'images/logo.png' %}" alt=""></div>
        </div>
        <div class="nav_right">
            <a href="">
                <div class="sub"><b>ACADEMY</b></div>
            </a>
            <a href="{% url 'user:info' %}">
                <div class="sub"><b>INFO</b></div>
            </a>
            <a href="">
                <div class="sub"><b>MORE</b></div>
            </a>
            <a href="{% url 'user:login' %}"><button class="btn">Login</button></a>
        </div>

    </div>


    {% block bodytext %}
    {% endblock %}

    <hr id="hr_1">

    <div class="view_more">
        <a href="{% url 'user:signup' %}">    
            <B>

                {% block downlinetext %}
                {% endblock %}

            </B>
         </a>
    </div>

    <div class="footer">
        <div class="footer_text">
          <a href=""><b>CSK@gmail.com</b></a>
        </div>
        <div class="footer_text">
           <a href=""><b>Terms & condition</b></a>
            <b class="white">|</b>
            <a href=""><b>Contact</b></a> 
            <b class="white">|</b>
            <a href=""><b>Privacy policy</b></a>
            <b class="white">|</b>
            <a href=""><b>Disclaimer</b></a>
        </div>
    </div>
        
</body>
</html>

project/user/templates/user_templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chennai Super Kings</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
    <div id="nav_bar">
        <div class="nav_left">
            <a href="{% url 'user:signup' %}"><button class="btn">Sign Up</button></a>
            <a href="{% url 'user:home' %}"><div class="sub"><b>HOME</b></div></a>
            <a href=""><div class="sub"><b>TEAM</b></div></a>
            <a href="{% url 'user:shop' %}"><div class="sub"><b>SHOP</b></div></a>
        </div>
        <div class="nav_center">
            <div class="nav_img"><img src="{% static 'images/logo.png' %}" alt=""></div>
        </div>
        <div class="nav_right">
            <a href=""><div class="sub"><b>ACADEMY</b></div></a>
            <a href="{% url 'user:info' %}"><div class="sub"><b>INFO</b></div></a>
            <a href=""><div class="sub"><b>MORE</b></div></a>
            <a href="{% url 'user:login' %}"><button class="btn">Login</button></a>
        </div>
        
    </div>



    <div class="marquee">
        <marquee behavior="" direction=""><img id="marquee_img" src="{% static 'images/marquee.png' %}" alt=""></marquee> 
    </div>

    <div id="latest_news">
         <b>LATEST NEWS</b>
    </div>
    <div class="container">
        <div class="card"><img src="{% static 'images/card1.jpg' %}" alt=""><b>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolore, voluptatem.</b></div>
        <div class="card"><img src="{% static 'images/card2.webp' %}" alt=""><b>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptate, illo!</b></div>
        <div class="card"><img src="{% static 'images/card3.jpg' %}" alt=""><b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod, ducimus!</b></div>
        <div class="card"><img src="{% static 'images/card5.jpg' %}" alt=""><b>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Molestiae, ipsa.</b></div>
        <div class="card"><img src="{% static 'images/card6.png' %}" alt=""><b>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nam, sit!</b></div>
        <div class="card"><img src="{% static 'images/card1.jpg' %}" alt=""><b>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda, repudiandae.</b></div>
        <div class="card"><img src="{% static 'images/card2.webp' %}" alt=""><b>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Fugit, pariatur.</b></div>
        <div class="card"><img src="{% static 'images/card3.jpg' %}" alt=""><b>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Culpa, praesentium?</b></div>
        <div class="card"><img src="{% static 'images/card5.jpg' %}" alt=""><b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, quam!</b></div>
        <div class="card"><img src="{% static 'images/card1.jpg' %}" alt=""><b>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda, repudiandae.</b></div>
        <div class="card"><img src="{% static 'images/card3.jpg' %}" alt=""><b>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod, ducimus!</b></div>
        <div class="card"><img src="{% static 'images/card6.png' %}" alt=""><b>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Omnis, placeat.</b></div>
    </div>

    <hr>

    <div class="shop_the_best">SHOP THE BEST</div>

    <div class="container_shop">

        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>

        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>

        
        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>

        
        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>
    </div>

    <hr id="hr_1">

    <div class="view_more">
        <a href="{% url 'user:shop' %}">    
            <B>SHOP NOW | MORE OFFERS</B>
         </a>
    </div>

    <div class="footer">
        <div class="footer_text">
          <a href=""><b>CSK@gmail.com</b></a>
        </div>
        <div class="footer_text">
           <a href=""><b>Terms & condition</b></a>
            <b class="white">|</b>
            <a href=""><b>Contact</b></a> 
            <b class="white">|</b>
            <a href=""><b>Privacy policy</b></a>
            <b class="white">|</b>
            <a href=""><b>Disclaimer</b></a>
        </div>
    </div>
</body>
</html>

project/user/templates/user_templates/info.html
{% extends 'user_templates/expage.html' %}


{% block title %} CSK | INFO {% endblock %}

{% block bodytext %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> </title>
    <link rel="stylesheet" href="{% static 'css/info.css' %}">
</head>

<body>
    <div class="container">

        <div class="info_note">
            <p>1 . Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis, quibusdam!</p>
        </div>
        <div class="info_note">
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestias omnis soluta doloremque nulla nihil
                porro enim. Nemo, quis. Ab tenetur amet magni ducimus minima facere quia dignissimos ipsum molestias
                veritatis.</p>
        </div>
        <div class="info_note">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia aliquid eius natus possimus cum illo
                aperiam tempora dolorem rem temporibus assumenda voluptatem sunt obcaecati vero incidunt nobis,
                laboriosam beatae, impedit animi molestiae sit! Fugiat, cupiditate vel praesentium natus blanditiis
                ullam voluptatum assumenda neque quis. Reiciendis blanditiis minima quidem. Corrupti porro neque saepe,
                libero sed voluptates itaque harum nobis non omnis unde, quidem suscipit ipsa molestiae dolores
                obcaecati at aperiam incidunt nisi, ipsum temporibus tenetur? Nam tempora saepe possimus dolor quaerat.
            </p>
        </div>
        <div class="info_note">
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo enim, dicta impedit magnam nemo
                cupiditate doloribus deserunt facere odit. Obcaecati!</p>
        </div>
        <div class="info_note">
            <p>1 . Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis, quibusdam!</p>
        </div>
        <div class="info_note">
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestias omnis soluta doloremque nulla nihil
                porro enim. Nemo, quis. Ab tenetur amet magni ducimus minima facere quia dignissimos ipsum molestias
                veritatis.</p>
        </div>
        <div class="info_note">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia aliquid eius natus possimus cum illo
                aperiam tempora dolorem rem temporibus assumenda voluptatem sunt obcaecati vero incidunt nobis,
                laboriosam beatae, impedit animi molestiae sit! Fugiat, cupiditate vel praesentium natus blanditiis
                ullam voluptatum assumenda neque quis. Reiciendis blanditiis minima quidem. Corrupti porro neque saepe,
                libero sed voluptates itaque harum nobis non omnis unde, quidem suscipit ipsa molestiae dolores
                obcaecati at aperiam incidunt nisi, ipsum temporibus tenetur? Nam tempora saepe possimus dolor quaerat.
            </p>
        </div>
        <div class="info_note">
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo enim, dicta impedit magnam nemo
                cupiditate doloribus deserunt facere odit. Obcaecati!</p>
        </div>
        <div class="info_note">
            <p>1 . Lorem ipsum, dolor sit amet consectetur adipisicing elit. Debitis, quibusdam!</p>
        </div>
        <div class="info_note">
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestias omnis soluta doloremque nulla nihil
                porro enim. Nemo, quis. Ab tenetur amet magni ducimus minima facere quia dignissimos ipsum molestias
                veritatis.</p>
        </div>
        <div class="info_note">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia aliquid eius natus possimus cum illo
                aperiam tempora dolorem rem temporibus assumenda voluptatem sunt obcaecati vero incidunt nobis,
                laboriosam beatae, impedit animi molestiae sit! Fugiat, cupiditate vel praesentium natus blanditiis
                ullam voluptatum assumenda neque quis. Reiciendis blanditiis minima quidem. Corrupti porro neque saepe,
                libero sed voluptates itaque harum nobis non omnis unde, quidem suscipit ipsa molestiae dolores
                obcaecati at aperiam incidunt nisi, ipsum temporibus tenetur? Nam tempora saepe possimus dolor quaerat.
            </p>
        </div>
       


    </div>
</body>

</html>

{% endblock %}

{% block downlinetext %}

    SHOP NOW  | SIGN UP

{% endblock %}

project/user/templates/user_templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSK | Login page</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">

</head>

<body>

    <div class="container_login">
        <div class="login_box">
            <div class="part_1">
                <img src="{% static 'images/logo.png' %}" alt="">
            </div>
            <div class="part_2">

                <div class="part_2_text">
                    <b id="join_the_text">Join the <br>#Yellove family</b>
                    <div>
                        <form action="">
                            <input type="email" name="" id="input_1" placeholder="  Email" required>

                            <input type="password" name="" id="input_2" placeholder="  Password" required>

                            <div>
                                <a style="text-decoration: none;" href=""><b id="forgot_pass">Forgot Password?</b></a>
                            </div>
                            <div id="container_btn-2">
                                <button type="submit" id="btn_2">LOGIN</button>
                            </div>
                        </form>
                        <div id="sign_up">
                            <a href="{% url 'user:signup' %}"><b id="sign_btn">Sign Up</b></a>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>



</body>

</html>

project/user/templates/user_templates/shop.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SHOPPING</title>
    <link rel="stylesheet" href="{% static 'css/shop.css' %}">
</head>

<body>

    
    <div id="nav_bar">
        <div class="nav_left">
            <a href="{% url 'user:signup' %}"><button class="btn">Sign Up</button></a>
            <a href="{% url 'user:home' %}">
                <div class="sub"><b>HOME</b></div>
            </a>
            <a href="">
                <div class="sub"><b>TEAM</b></div>
            </a>
            <a href="{% url 'user:shop' %}">
                <div class="sub"><b>SHOP</b></div>
            </a>
        </div>
        <div class="nav_center">
            <div class="nav_img"><img src="{% static 'images/logo.png' %}" alt=""></div>
        </div>
        <div class="nav_right">
            <a href="">
                <div class="sub"><b>ACADEMY</b></div>
            </a>
            <a href="{% url 'user:info' %}">
                <div class="sub"><b>INFO</b></div>
            </a>
            <a href="">
                <div class="sub"><b>MORE</b></div>
            </a>
            <a href="{% url 'user:login' %}"><button class="btn">Login</button></a>
        </div>

    </div>

    <div id="div_marquee">
    
        <marquee id="marquee" behavior="" direction=""><h2>OFFER AREA % OFF</h2></marquee>

    </div>


    <div class="container_shop">

        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>

        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>

        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>


        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>

        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>

        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>


        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>

        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>

        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>

        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>

        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>

        <div class="shop">
            <div>
            <img src="{% static 'images/sale1.png' %}" alt="">
            </div>
           <div class="shop_now"><button>SHOP NOW</button></div>
        </div>
    </div>

    <!-- footer area -->
    <hr id="hr_1">

    <div class="view_more">
        <a href="{% url 'user:signup' %}">    
            <B>JOIN NOW | CSK</B>
         </a>
    </div>

    <div class="footer">
        <div class="footer_text">
          <a href=""><b>CSK@gmail.com</b></a>
        </div>
        <div class="footer_text">
           <a href=""><b>Terms & condition</b></a>
            <b class="white">|</b>
            <a href=""><b>Contact</b></a> 
            <b class="white">|</b>
            <a href=""><b>Privacy policy</b></a>
            <b class="white">|</b>
            <a href=""><b>Disclaimer</b></a>
        </div>
    </div>
    <!-- footer area end -->
</body>

</html>

project/user/templates/user_templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CSK | create </title>
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
</head>

<body>
    <div class="container" >
        <div class="box_form">
            


            <table id="table">
                <form action="">
                    <tr>
                        <td colspan="3"><h2>Sign Up</h2></td>
                    </tr>
                    <tr>
                        <td>
                            <label class="t_text" for="first_name">First name</label>
                        </td>
                        <td>
                            :
                        </td>
                        <td>
                            <input class="t-input" type="text" id="first_name" required>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <label class="t_text" for="2nd_name">2nd name</label>
                        </td>
                        <td>
                            :
                        </td>
                        <td>
                            <input class="t-input" type="text" id="2nd_name" required>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label class="t_text" for="ph_numbre">Phone</label>
                        </td>
                        <td>
                            :
                        </td>
                        <td>
                            <input class="t-input" type="number" id="ph_number" required>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label class="t_text" for="mail">E-mail</label>
                        </td>
                        <td>
                            :
                        </td>
                        <td>
                            <input class="t-input" type="email" id="email" required>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label class="t_text" for="pass">Password</label>
                        </td>
                        <td>
                            :
                        </td>
                        <td>
                            <input class="t-input" type="password" id="pass" required>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label class="t_text" for="re_pass">Re-enter</label>
                        </td>
                        <td>
                            :
                        </td>
                        <td>
                            <input class="t-input" type="password" id="re_pass" required>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3">
                            <button id="btn_sign" type="submit">Sign Up</button>
                        </td>
                    </tr>
                </form>
            </table>
        </div>
    </div>

    <div class="para"><a href="{% url 'user:home' %}"><p>Back to home page..</p></a></div>



</body>

</html>